# Generated by Django 5.1.15 on 2026-05-03 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
        ("tasks", "0006_taskdependency"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=64)),
                ("message", models.TextField()),
                ("actor_name_snapshot", models.CharField(blank=True, max_length=255, null=True)),
                ("project_code_snapshot", models.CharField(blank=True, max_length=32, null=True)),
                ("project_name_snapshot", models.CharField(blank=True, max_length=255, null=True)),
                ("task_key_snapshot", models.CharField(blank=True, max_length=64, null=True)),
                ("task_title_snapshot", models.CharField(blank=True, max_length=255, null=True)),
                ("related_user_name_snapshot", models.CharField(blank=True, max_length=255, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="activity_entries", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "project",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="activity_entries", to="projects.project"),
                ),
                (
                    "task",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="activity_entries", to="tasks.task"),
                ),
            ],
            options={
                "db_table": "activity_logs",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["project", "created_at"], name="activity_lo_project_53821a_idx"),
                    models.Index(fields=["task", "created_at"], name="activity_lo_task_id_65dc85_idx"),
                    models.Index(fields=["event_type"], name="activity_lo_event_t_1f8f28_idx"),
                ],
            },
        ),
    ]
