# Generated by Django 5.1.15 on 2026-05-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='activity_lo_project_80b048_idx',
            old_name='activity_lo_project_53821a_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='activity_lo_task_id_aba60f_idx',
            old_name='activity_lo_task_id_65dc85_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='activity_lo_event_t_dca05e_idx',
            old_name='activity_lo_event_t_1f8f28_idx',
        ),
    ]
