# Generated by Django 5.1.15 on 2026-05-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_7336fd_idx',
            old_name='notificatio_user_id_2b6ef5_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_5cf777_idx',
            old_name='notificatio_user_id_046ac6_idx',
        ),
    ]
