# Generated by Django 5.1.15 on 2026-05-03 06:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_workflow_metadata(apps, schema_editor):
    TaskPriority = apps.get_model("tasks", "TaskPriority")
    TaskWorkflowStatus = apps.get_model("tasks", "TaskWorkflowStatus")
    TaskStatusTransition = apps.get_model("tasks", "TaskStatusTransition")

    statuses = {}
    for payload in [
        {"name": "TODO", "sort_order": 1, "is_final": False},
        {"name": "IN_PROGRESS", "sort_order": 2, "is_final": False},
        {"name": "DONE", "sort_order": 3, "is_final": True},
    ]:
        status, _ = TaskWorkflowStatus.objects.get_or_create(
            name=payload["name"],
            defaults=payload,
        )
        statuses[payload["name"]] = status

    for payload in [
        {"name": "LOW", "sort_order": 1},
        {"name": "MEDIUM", "sort_order": 2},
        {"name": "HIGH", "sort_order": 3},
        {"name": "URGENT", "sort_order": 4},
    ]:
        TaskPriority.objects.get_or_create(
            name=payload["name"],
            defaults=payload,
        )

    for payload in [
        {
            "from_status": statuses["TODO"],
            "to_status": statuses["IN_PROGRESS"],
            "name": "Start work",
        },
        {
            "from_status": statuses["IN_PROGRESS"],
            "to_status": statuses["DONE"],
            "name": "Complete task",
        },
        {
            "from_status": statuses["DONE"],
            "to_status": statuses["IN_PROGRESS"],
            "name": "Reopen task",
        },
    ]:
        TaskStatusTransition.objects.get_or_create(
            from_status=payload["from_status"],
            to_status=payload["to_status"],
            defaults={"name": payload["name"], "is_active": True},
        )


def backfill_task_statuses(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    TaskWorkflowStatus = apps.get_model("tasks", "TaskWorkflowStatus")

    status_map = {
        status.name: status.id
        for status in TaskWorkflowStatus.objects.all()
    }
    default_status_id = status_map["TODO"]

    for task in Task.objects.all():
        task.status_catalog_id = status_map.get(task.status, default_status_id)
        task.save(update_fields=["status_catalog"])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_projects_pro_owner_i_5ca346_idx_projects_owner_i_c299b3_idx_and_more'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPriority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('sort_order', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'task_priorities',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['sort_order'], name='task_priori_sort_or_7e0c1a_idx'), models.Index(fields=['is_active'], name='task_priori_is_acti_4b58c5_idx')],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskpriority'),
        ),
        migrations.CreateModel(
            name='TaskWorkflowStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('sort_order', models.PositiveIntegerField()),
                ('is_final', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'task_statuses',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['sort_order'], name='task_status_sort_or_60deef_idx'), models.Index(fields=['is_active'], name='task_status_is_acti_fb27b7_idx')],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='status_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='tasks.taskworkflowstatus'),
        ),
        migrations.CreateModel(
            name='TaskStatusTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='outgoing_transitions', to='tasks.taskworkflowstatus')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='incoming_transitions', to='tasks.taskworkflowstatus')),
            ],
            options={
                'db_table': 'task_status_transitions',
                'ordering': ['from_status__sort_order', 'to_status__sort_order', 'name'],
            },
        ),
        migrations.RunPython(seed_workflow_metadata, migrations.RunPython.noop),
        migrations.RunPython(backfill_task_statuses, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='status_catalog',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to='tasks.taskworkflowstatus'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_status__607ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='tasks_priorit_f06d2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskstatustransition',
            constraint=models.UniqueConstraint(fields=('from_status', 'to_status'), name='unique_task_status_transition'),
        ),
        migrations.AddConstraint(
            model_name='taskstatustransition',
            constraint=models.CheckConstraint(condition=models.Q(('from_status', models.F('to_status')), _negated=True), name='task_status_transition_no_self_reference'),
        ),
    ]
