# Generated by Django 5.1.15 on 2026-05-03 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskpriority_task_priority_taskworkflowstatus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_collaborators', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='task_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_collaborators',
                'ordering': ['task_id', 'user_id'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborating_tasks', through='tasks.TaskCollaborator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='taskcollaborator',
            index=models.Index(fields=['task'], name='task_collab_task_id_f564e0_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcollaborator',
            index=models.Index(fields=['user'], name='task_collab_user_id_665ba1_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskcollaborator',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='unique_task_collaborator_per_user'),
        ),
    ]
