# Generated by Django 5.1.15 on 2026-05-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_parent_task'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_parent__ebc03e_idx',
            old_name='tasks_task_parent__ddcf5b_idx',
        ),
    ]
