# Generated by Django 5.1.15 on 2026-05-03 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_rename_tasks_task_parent__ddcf5b_idx_tasks_parent__ebc03e_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskDependency",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "depends_on_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_dependency_links",
                        to="tasks.task",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependency_links",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "task_dependencies",
                "ordering": ["task_id", "depends_on_task_id"],
                "indexes": [models.Index(fields=["task"], name="task_depende_task_id_876e48_idx"), models.Index(fields=["depends_on_task"], name="task_depende_depends_39a763_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("task", "depends_on_task"), name="unique_task_dependency"),
                    models.CheckConstraint(condition=models.Q(("task", models.F("depends_on_task")), _negated=True), name="task_dependency_no_self_reference"),
                ],
            },
        ),
    ]
