# Generated by Django 5.1.15 on 2026-05-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskdependency'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='taskdependency',
            new_name='task_depend_task_id_52f414_idx',
            old_name='task_depende_task_id_876e48_idx',
        ),
        migrations.RenameIndex(
            model_name='taskdependency',
            new_name='task_depend_depends_53442a_idx',
            old_name='task_depende_depends_39a763_idx',
        ),
    ]
