# Generated by Django 5.1.15 on 2026-05-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='comments_task_id_62c144_idx',
            old_name='comments_task_cr_4e5fbf_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='comments_author__25752a_idx',
            old_name='comments_author__3a4ba0_idx',
        ),
    ]
